name: Build and Deploy Vite Project

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  pages: write

jobs:
  test-and-build:
    uses: ./.github/workflows/test-and-build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: test-and-build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
